# Exported from Render on 2026-07-12T13:28:30Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: dukuduku-app
      runtime: node
      repo: https://github.com/sakhamnima/dukuduku-app
      plan: free
      region: singapore
      buildCommand: npm install
      startCommand: npm start
      autoDeployTrigger: commit
      rootDir: src
      previews:
        generation: automatic
